// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Chakra_Petch } from "next/font/google";
import Header from "./components/layout/Header/Header";
import Footer from "./components/layout/Footer/Footer";
import { AuthProvider } from "./context/AuthContext";

import AuthModal from "./components/Auth/AuthModal";
import "./styles/_transitions.scss";

const chakraPetch = Chakra_Petch({
  subsets: ["latin"],
  weight: ["300", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <AuthProvider>
      <body className={chakraPetch.className}>
          <Header />
          <main style={{ paddingTop: 60 }}>{children}</main>
          <Footer />
          <AuthModal />
      </body>
        </AuthProvider>
    </html>
  );
}
