// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Chakra_Petch } from "next/font/google";
import Header from "./components/layout/Header/Header";
import Footer from "./components/layout/Footer/Footer";
import { AuthProvider } from "./context/AuthContext";
import { Toaster } from "react-hot-toast";

import AuthModal from "./components/Auth/AuthModal";
import "./styles/_transitions.scss";
import { ModalProvider } from "./context/ModalContext";
import AppModal from "./components/commen/AppModal/AppModal";

const chakraPetch = Chakra_Petch({
  subsets: ["latin"],
  weight: ["300", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <ModalProvider>
          <body className={chakraPetch.className}>
            <Header />
            <main style={{ paddingTop: 60 }}>{children}</main>
            <Toaster
              position="bottom-center"
              reverseOrder={false}
              toastOptions={{
                style: {
                  zIndex: 101,
                },
              }}
            />
            <Footer />
            <AuthModal />
            <AppModal />
          </body>
        </ModalProvider>
      </AuthProvider>
    </html>
  );
}
