import { Product } from "../types";

const products: Product[] = [
  {
    id: "1",
    name: "AK-47",
    wear: "Minimal Wear",
    wearValue: 0.05,
    price: 100.0,
    priceChange: "+6%",
    priceChangeValue: 6,
    image: "/images/gloves-sample2.png",
    type: "Gloves",
    skinType: "Emerlad",
    discountPercentage: -10,
    color: "Green500",
    deliveryTime: "0-10 min",
  },
  {
    id: "2",
    name: "M4A4",
    wear: "Field-Tested",
    wearValue: 0.2,
    price: 200.0,
    priceChange: "+6%",
    priceChangeValue: 6,
    image: "/images/gloves-sample.png",
    type: "Gloves",
    skinType: "Emerlad",
    discountPercentage: 3,
    color: "Blood500",
    deliveryTime: "0-30 min",
  },
  {
    id: "3",
    name: "AWP",
    wear: "Battle-Scarred",
    wearValue: 0.7,
    price: 1400.0,
    priceChange: "+3%",
    priceChangeValue: 3,
    image: "/images/rifles-sample2.png",
    type: "Rifles",
    skinType: "Emerlad",
    discountPercentage: 10,
    color: "Sky500",
    deliveryTime: "0-12 hrs",
  },
  {
    id: "4",
    name: "AK-47",
    wear: "Minimal Wear",
    wearValue: 0.1,
    price: 230.0,
    priceChange: "+3%",
    priceChangeValue: 3,
    image: "/images/rifles-sample.png",
    type: "Rifles",
    skinType: "Emerlad",
    discountPercentage: -5,
    color: "Yellow500",
    deliveryTime: "0-10 min",
  },
  {
    id: "5",
    name: "Glock-18",
    wear: "Well-Worn",
    wearValue: 0.4,
    price: 100.99,
    priceChange: "+3%",
    priceChangeValue: 3,
    image: "/images/pinstol-sample.png",
    type: "Pistols",
    skinType: "Emerlad",
    discountPercentage: 0,
    color: "Green400",
    deliveryTime: "0-30 min",
  },
  {
    id: "6",
    name: "Navaja Knife",
    wear: "Factory New",
    wearValue: 0.02,
    price: 1230.1,
    priceChange: "+3%",
    priceChangeValue: 3,
    image: "/images/knives-sample.png",
    type: "Knives",
    skinType: "Fade",
    discountPercentage: -20,
    color: "Primary500",
    deliveryTime: "0-10 min",
  },
  {
    id: "7",
    name: "UMP-45",
    wear: "Field-Tested",
    wearValue: 0.3,
    price: 1230.1,
    priceChange: "+3%",
    priceChangeValue: 3,
    image: "/images/gun1.png",
    type: "Mid-Tier",
    skinType: "Emerald",
    discountPercentage: 5,
    color: "Lake500",
    deliveryTime: "0-12 hrs",
  },
  {
    id: "8",
    name: "MP9",
    wear: "Minimal Wear",
    wearValue: 0.1,
    price: 1230.1,
    priceChange: "+3%",
    priceChangeValue: 3,
    image: "/images/s1.png",
    type: "Mid-Tier",
    skinType: "Emerald",
    discountPercentage: -8,
    color: "Pink500",
    deliveryTime: "0-10 min",
  },
  {
    id: "9",
    name: "Desert Eagle",
    wear: "Well-Worn",
    wearValue: 0.59,
    price: 1230.1,
    priceChange: "+3%",
    priceChangeValue: 3,
    image: "/images/s2.png",
    type: "Pistols",
    skinType: "Emerald",
    discountPercentage: 15,
    color: "Sun500",
    deliveryTime: "0-30 min",
  },
  {
    id: "10",
    name: "AWP",
    wear: "Battle-Scarred",
    wearValue: 0.3,
    price: 1230.1,
    priceChange: "+3%",
    priceChangeValue: 3,
    image: "/images/s3.png",
    type: "Rifles",
    skinType: "Emerald",
    discountPercentage: 2,
    color: "Yellow500",
    deliveryTime: "0-10 min",
  },
  // Duplicated products to reach 20 items
  {
    id: "11",
    name: "AK-47",
    wear: "Minimal Wear",
    wearValue: 0.06, // Slightly different wear value
    price: 110.0,
    priceChange: "+5%",
    priceChangeValue: 5,
    image: "/images/gloves-sample2.png",
    type: "Gloves",
    skinType: "Emerlad",
    discountPercentage: -12,
    color: "Green500",
    deliveryTime: "0-10 min",
  },
  {
    id: "12",
    name: "M4A4",
    wear: "Field-Tested",
    wearValue: 0.25,
    price: 210.0,
    priceChange: "+7%",
    priceChangeValue: 7,
    image: "/images/gloves-sample.png",
    type: "Gloves",
    skinType: "Emerlad",
    discountPercentage: 4,
    color: "Blood500",
    deliveryTime: "0-30 min",
  },
  {
    id: "13",
    name: "AWP",
    wear: "Battle-Scarred",
    wearValue: 0.75,
    price: 1450.0,
    priceChange: "+4%",
    priceChangeValue: 4,
    image: "/images/rifles-sample2.png",
    type: "Rifles",
    skinType: "Emerlad",
    discountPercentage: 11,
    color: "Sky500",
    deliveryTime: "0-12 hrs",
  },
  {
    id: "14",
    name: "AK-47",
    wear: "Minimal Wear",
    wearValue: 0.12,
    price: 240.0,
    priceChange: "+4%",
    priceChangeValue: 4,
    image: "/images/rifles-sample.png",
    type: "Rifles",
    skinType: "Emerlad",
    discountPercentage: -6,
    color: "Yellow500",
    deliveryTime: "0-10 min",
  },
  {
    id: "15",
    name: "Glock-18",
    wear: "Well-Worn",
    wearValue: 0.42,
    price: 105.99,
    priceChange: "+4%",
    priceChangeValue: 4,
    image: "/images/pinstol-sample.png",
    type: "Pistols",
    skinType: "Emerlad",
    discountPercentage: 1,
    color: "Green400",
    deliveryTime: "0-30 min",
  },
  {
    id: "16",
    name: "Navaja Knife",
    wear: "Factory New",
    wearValue: 0.03,
    price: 1240.1,
    priceChange: "+4%",
    priceChangeValue: 4,
    image: "/images/knives-sample.png",
    type: "Knives",
    skinType: "Fade",
    discountPercentage: -22,
    color: "Primary500",
    deliveryTime: "0-10 min",
  },
  {
    id: "17",
    name: "UMP-45",
    wear: "Field-Tested",
    wearValue: 0.33,
    price: 1240.1,
    priceChange: "+4%",
    priceChangeValue: 4,
    image: "/images/gun1.png",
    type: "Mid-Tier",
    skinType: "Emerald",
    discountPercentage: 6,
    color: "Lake500",
    deliveryTime: "0-12 hrs",
  },
  {
    id: "18",
    name: "MP9",
    wear: "Minimal Wear",
    wearValue: 0.12,
    price: 1240.1,
    priceChange: "+4%",
    priceChangeValue: 4,
    image: "/images/s1.png",
    type: "Mid-Tier",
    skinType: "Emerald",
    discountPercentage: -9,
    color: "Pink500",
    deliveryTime: "0-10 min",
  },
  {
    id: "19",
    name: "Desert Eagle",
    wear: "Well-Worn",
    wearValue: 0.61,
    price: 1240.1,
    priceChange: "+4%",
    priceChangeValue: 4,
    image: "/images/s2.png",
    type: "Pistols",
    skinType: "Emerald",
    discountPercentage: 16,
    color: "Sun500",
    deliveryTime: "0-30 min",
  },
  {
    id: "20",
    name: "AWP",
    wear: "Battle-Scarred",
    wearValue: 0.33,
    price: 1240.1,
    priceChange: "+4%",
    priceChangeValue: 4,
    image: "/images/s3.png",
    type: "Rifles",
    skinType: "Emerald",
    discountPercentage: 3,
    color: "Yellow500",
    deliveryTime: "0-10 min",
  },
];

export default products;

