const ImagePaths = {
  // Logos and general branding
  logos: {
    logo: "/images/Logo.svg",
  },
  // Icons
  icons: {
    pack: "/images/Pack.svg",
    weapons: "/images/Weapons.svg",
    weapons2: "/images/Weapons2.svg",
    angle: "/images/angle.png", // PNG
    arrowDown: "/images/arrow-down.svg",
    arrowDown2: "/images/arrow-down2.svg",
    arrowRightCircle: "/images/arrow-right-circle.svg",
    arrowUp: "/images/arrow-up.svg",
    arrowUp2: "/images/arrow-up2.svg",
    blackMark: "/images/blackMark.svg",
    categories: "/images/categories.svg",
    categoryGray: "/images/category-gray.svg",
    coin: "/images/coin.svg",
    cup: "/images/cup.svg",
    done: "/images/done.svg",
    envelope: "/images/envelope.svg",
    mark: "/images/mark.svg",
    merchant: "/images/merchant.svg",
    plusCircle: "/images/plus-circle.svg",
    refresh: "/images/refresh.svg",
    search: "/images/search.svg",
    sliders: "/images/sliders.svg",
    sort: "/images/sort.svg",
    trade: "/images/trade.svg",
    trash: "/images/trash.svg",
    xMark: "/images/x-mark.svg",
    xMark2: "/images/x-mark2.svg",
    user: "/images/user.svg",
    lockClose: "/images/lock-close.svg",
    steam: "/images/steam.svg",
    google: "/images/google.svg",
    discord: "/images/discord.svg",
    eyeOff: "/images/eye-off.svg",
    eyeOn: "/images/eye-off.svg",
    autoTrade: "/images/arrow-path.svg",
    p2p: "/images/handshake.svg",
    deliveryRate: "/images/delivery-rate.svg",
    deliveryTime: "/images/delivery-time.svg",
    tradeNotification: "/images/trade-notification.svg",
    tradeMode: "/images/trade-mode.svg",
    xRed: "/images/x-red.svg",
    checkCircle: "/images/check-circle.svg",
    plus: "/images/plus.svg",
  },
  // Product type icons
  productTypes: {
    cases: "/images/cases.svg",
    gloves: "/images/gloves.svg",
    knife: "/images/knife.svg",
    midTier: "/images/mid-tier.svg",
    pistol: "/images/pistol.svg",
    rifles: "/images/rifles.svg",
  },
  // Delivery icons
  delivery: {
    deliveryFast: "/images/delivery-fast.svg",
    deliveryNormal: "/images/delivery-normal.svg",
    express: "/images/express.svg",
    fast: "/images/fast.svg",
    normal: "/images/normal.svg",
  },
  // Sample product images
  productSamples: {
    glovesSample: "/images/gloves-sample.png",
    glovesSample2: "/images/gloves-sample2.png",
    gun1: "/images/gun1.png",
    knivesSample: "/images/knives-sample.png",
    pinstolSample: "/images/pinstol-sample.png",
    riflesSample: "/images/rifles-sample.png",
    riflesSample2: "/images/rifles-sample2.png",
    s1: "/images/s1.png",
    s2: "/images/s2.png",
    s3: "/images/s3.png",
    symbol1: "/images/symbol1.png",
  },
  // Social media icons
  social: {
    facebook: "/images/facebook.svg",
    instagram: "/images/instagram.svg",
    linkedin: "/images/linkedin.svg",
    twitter: "/images/twitter.svg",
    youtube: "/images/youtube.svg",
  },
  // Other general images
  general: {
    cover: "/images/cover.jpg",
    tradePng: "/images/trade.png",
    authBanner: "/images/authBanner.svg",
    authPattern: "/images/authPattern.svg",
    lightStarBg: "/images/light-star-bg.png",
  },
  deposit: {
    cs2go: "/images/deposit-cs2go.png",
    rust: "/images/deposit-rust.png",
    dota2: "/images/deposit-dota2.png",
  },
  crypto: {
    bitcoin: "/images/crypto/bitcoin.svg",
    tether: "/images/crypto/tether.svg",
    binance: "/images/crypto/binance.svg",
    ethereum: "/images/crypto/ethereum.svg",
    dogecoin: "/images/crypto/dogecoin.svg",
    liteCoin: "/images/crypto/liteCoin.svg",
    solana: "/images/crypto/solana.svg",
    cardano: "/images/crypto/cardano.svg",
    ripple: "/images/crypto/ripple.svg",
    more: "/images/crypto/more.svg",
  },
  cash: {
    visa: "/images/cash/visacard.svg",
    mastercard: "/images/cash/mastercard.svg",
    paypal: "/images/cash/paypal.svg",
    applepay: "/images/cash/applepay.svg",
    googlepay: "/images/cash/googlepay.svg",
  },
};

export default ImagePaths;
